################################################################################################################
# IMS Api Kakao
################################################################################################################

server:
  port: 39001

logging:
  #config: file:${user.dir}/logback-spring.xml
  config: classpath:logback-spring.xml

spring:
  application:
    # application \uBA85\uCE6D\uC124\uC815
    name: IMS-API-KAKAO

  banner:
    #location: file:${user.dir}/banner.txt
    location: classpath:banner.txt
    charset: UTF-8

  boot:
    admin:
      client:
        # spring boot admin \uC11C\uBC84 \uC124\uC815
        url: http://127.0.0.1:29000
        username: admin
        password: admin12#$
        instance:
          prefer-ip: true
          metadata:
            user.name: admin
            user.password: admin12#$

  # Redis
  redis:
    host: localhost
    port: 6379
    database: 0
#    password:
#    client-type: lettuce
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 2
#        max-wait: -1ms
#      shutdown-timeout: 100ms

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

ims:
  api:
    kakao:
      service-name: "API-KAKAO"
