################################################################################################################
# IMS Api Kakao
################################################################################################################

server:
  port: 39001

logging:
  #config: file:${user.dir}/logback-spring.xml
  config: classpath:logback-spring.xml

spring:
  application:
    # application \uBA85\uCE6D\uC124\uC815
    name: IMS-API-KAKAO

  banner:
    #location: file:${user.dir}/banner.txt
    location: classpath:banner.txt
    charset: UTF-8

  boot:
    admin:
      client:
        # spring boot admin \uC11C\uBC84 \uC124\uC815
        url: http://127.0.0.1:29000
        username: admin
        password: admin12#$
        instance:
          prefer-ip: true
          metadata:
            user.name: admin
            user.password: admin12#$

  kafka:
#    bootstrap-servers: "127.0.0.1:9092"
    bootstrap-servers: "10.147.1.90:9092"
    producer:
      client-id: "V1.API.KAKAO"
      retries: 0
      batch-size: 20000
      compression-type: gzip
      linger-ms: 50
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1

  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: API-KAKAO-
      shutdown:
        await-termination: true
        await-termination-period: 60

  # Redis
  redis:
    host: localhost
    port: 6379
    database: 0
#    password:
#    client-type: lettuce
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 2
#        max-wait: -1ms
#      shutdown-timeout: 100ms

  # jackson naming strategy
  jackson:
    property-naming-strategy: SNAKE_CASE

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

ims:
  api:
    kakao:
      service-name: "API-KAKAO"
      scheduled:
        redis-load-service-key-info: "30 */1 * * * *"
        redis-load-template-code-info: "30 */1 * * * *"
        redis-load-send-profile-info: "30 */1 * * * *"

      # 토픽 리스트
      topics:
        recv-at:
          - RECV-AT
        recv-ft:
          - RECV-FT
        recv-bt:
          - RECV-BT
