################################################################################################################
# IMS CHANNEL-KAKAO
################################################################################################################

server:
  port: 40101
  shutdown: graceful

logging:
  #config: file:${user.dir}/logback-spring.xml
  config: classpath:logback-spring.xml

spring:
  application:
    name: IMS-CHANNEL-KAKAO

  banner:
    #location: file:${user.dir}/banner.txt
    location: classpath:banner.txt
    charset: UTF-8

  boot:
    admin:
      client:
        # spring boot admin \uC11C\uBC84 \uC124\uC815
        url: http://127.0.0.1:29000
        username: admin
        password: admin12#$
        instance:
          prefer-ip: true
          metadata:
            user.name: admin
            user.password: admin12#$

  kafka:
    bootstrap-servers: "127.0.0.1:9092"
    producer:
      client-id: "CHANNEL-KAKAO"
      retries: 0
      batch-size: 20000
      compression-type: gzip
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      properties:
        linger.ms: 50
    consumer:
      group-id: "CHANNEL-KAKAO"
#      client-id: "CHANNEL_KAKAO"
      enable-auto-commit: false
      max-poll-records: 500
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
#      isolation-level: read_committed
    listener:
      concurrency: 5
      ack-mode: manual_immediate
      poll-timeout: 3000
      type: single

  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: KAKAO-
      shutdown:
        await-termination: true
        await-termination-period: 60

  # Redis
  redis:
    host: localhost
    port: 6379
    database: 0
  #    password:
  #    client-type: lettuce
  #    lettuce:
  #      pool:
  #        max-active: 10
  #        max-idle: 10
  #        min-idle: 2
  #        max-wait: -1ms
  #      shutdown-timeout: 100ms


# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

ims:
  channel:
    kakao:
      simulation: true
      wiretap: false

      service-name: ${spring.application.name}
      base-url: "http://localhost:40101"
      at-path: "/at/sendMessage"
      ft-path: "/ft/sendMessage"
      bt-path: "/bt/sendMessage"

      ## milliseconds
      connect-timeout: 3s
      response-timeout: 3s
      read-timeout: 3s
      write-timeout: 3s


      # \uD1A0\uD53D \uB9AC\uC2A4\uD2B8
      topics:
        # \uBC1C\uC1A1(SEND) \uD1A0\uD53D\uC73C\uB85C \uCEE8\uC298
        send-at:
          - SEND-AT-DEFAULT
        send-ft:
          - SEND-FT-DEFAULT
        send-bt:
          - SEND-BT-DEFAULT