################################################################################################################
# IMS Router
################################################################################################################

server:
  port: 40000

logging:
  #config: file:${user.dir}/logback-spring.xml
  config: classpath:logback-spring.xml

spring:
  application:
    name: IMS-ROUTER

  banner:
    #location: file:${user.dir}/banner.txt
    location: classpath:banner.txt
    charset: UTF-8

  boot:
    admin:
      client:
        # spring boot admin \uC11C\uBC84 \uC124\uC815
        url: http://127.0.0.1:29000
        username: admin
        password: admin12#$
        instance:
          prefer-ip: true
          metadata:
            user.name: admin
            user.password: admin12#$

  kafka:
#    bootstrap-servers: "127.0.0.1:9092"
    bootstrap-servers: "10.147.1.90:9092"
    producer:
      client-id: "ROUTER"
      retries: 0
      batch-size: 20000
      compression-type: gzip
      linger-ms: 50
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
    consumer:
      group-id: "ROUTER"
      enable-auto-commit: false
      max-poll-records: 500
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 5
      ack-mode: manual_immediate
      poll-timeout: 3000
#      type: single
      # Custom setting - batch listener
      batch: false
      # Custom setting - auto startup listener
      auto-startup: true
    # Custom setting - retries
    retry:
      max-attempts: 10
      initial-interval: 1000
      multiplier: 2
      max-interval: 10000

  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: ROUTER-
      shutdown:
        await-termination: true
        await-termination-period: 60

  # Redis
  redis:
    host: localhost
    port: 6379
    database: 0
  #    password:
  #    client-type: lettuce
  #    lettuce:
  #      pool:
  #        max-active: 10
  #        max-idle: 10
  #        min-idle: 2
  #        max-wait: -1ms
  #      shutdown-timeout: 100ms


# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

ims:
  router:
    service-name: "ROUTER"

    # 토픽 리스트
    topics:
      recv-at:
        - RECV-AT
      recv-ft:
        - RECV-FT
      recv-bt:
        - RECV-BT
