################################################################################################################
# IMS API Gateway
################################################################################################################

server:
  port: 39001
  shutdown: graceful

logging:
  #config: file:${user.dir}/logback-spring.xml
  config: classpath:logback-spring.xml

spring:
  application:
    # application 명칭 설정
    name: IMS-API-GATEWAY

  banner:
    #location: file:${user.dir}/banner.txt
    location: classpath:banner.txt
    charset: UTF-8

  # gateway 설정
  cloud:
    gateway:
      filter:
        request-rate-limiter:
          deny-empty-key: true
          enabled: true
      discovery:
        locator:
          enabled: false
      routes:
        - id: v1-api-kakao
          uri: http://127.0.0.1:39001/
#          uri: lb://v1.api.kakao
          predicates:
            - Path=/ims/v1/**
#            - After=2020-01-01T00:00:00.000-09:00[Asia/Seoul]
#            - Before=2020-01-01T00:00:00.000-09:00[Asia/Seoul]
            - Between=2020-01-01T00:00:00.000-09:00[Asia/Seoul], 2020-12-31T00:00:00.000-09:00[Asia/Seoul]

          ## 어떻게 적용하는 지 모르겠다.
#          filter:
#            - name: RequestRateLimiter
#              args:
#                maxSize: 1
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1
#                key-resolver: "#{@keyResolver}"
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

  # Redis
  redis:
    host: localhost
    port: 6379
    database: 0
  #    password:
  #    client-type: lettuce
  #    lettuce:
  #      pool:
  #        max-active: 10
  #        max-idle: 10
  #        min-idle: 2
  #        max-wait: -1ms
  #      shutdown-timeout: 100ms

  boot:
    admin:
      client:
        # spring boot admin 서버 설정
        url: http://127.0.0.1:29000
        username: admin
        password: admin12#$
        instance:
          prefer-ip: true
          metadata:
            user.name: admin
            user.password: admin12#$

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
