################################################################################################################
# IMS Store
################################################################################################################

server:
  port: 39100
  shutdown: graceful

logging:
  #config: file:${user.dir}/logback-spring.xml
  config: classpath:logback-spring.xml

spring:
  application:
    # application \uBA85\uCE6D\uC124\uC815
    name: IMS-STORE

  banner:
    #location: file:${user.dir}/banner.txt
    location: classpath:banner.txt
    charset: UTF-8

  boot:
    admin:
      client:
        # spring boot admin \uC11C\uBC84 \uC124\uC815
        url: http://127.0.0.1:29000
        username: admin
        password: admin12#$
        instance:
          prefer-ip: true
          metadata:
            user.name: admin
            user.password: admin12#$

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ims?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 60000
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        globally_quoted_identifiers: true

    # Redis
  redis:
    host: localhost
    port: 6379
    database: 0
#    password:
#    client-type: lettuce
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 2
#        max-wait: -1ms
#      shutdown-timeout: 100ms

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

ims:
  store:
    service-name: ${spring.application.name}
