################################################################################################################
# IMS API MT (LOCAL)
################################################################################################################

server:
  port: 30401
  shutdown: graceful

logging:
  #config: file:${user.dir}/logback-spring.xml
  config: classpath:logback-spring.xml

spring:
  application:
    name: IMS-API-MT

  banner:
    #location: file:${user.dir}/banner.txt
    location: classpath:banner.txt
    charset: UTF-8

  boot:
    admin:
      client:
        # spring boot admin
        url: http://127.0.0.1:29000
        username: admin
        password: admin12#$
        instance:
          prefer-ip: true
          metadata:
            user.name: admin
            user.password: admin12#$

  kafka:
    bootstrap-servers:
      - 127.0.0.1:9092
    producer:
      client-id: "API-MT"
      retries: 100
      batch-size: 20000
      compression-type: gzip
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      properties:
        linger.ms: 50
        transaction.timeout.ms: 60000
        ## send 하는데 block 되는 시간 (default 60 * 1000 ms, 조절 할 필요 있을듯.)
        max.block.ms: 1000

  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: API-MT-
      shutdown:
        await-termination: true
        await-termination-period: 60

  # Redis
  redis:
    host: localhost
    port: 6379
    database: 0
  #    password:
  #    client-type: lettuce
  #    lettuce:
  #      pool:
  #        max-active: 10
  #        max-idle: 10
  #        min-idle: 2
  #        max-wait: -1ms
  #      shutdown-timeout: 100ms

  # jackson naming strategy
  jackson:
    property-naming-strategy: SNAKE_CASE

## eureka
eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    should-unregister-on-shutdown: true

  instance:
    prefer-ip-address: true
    ## Heart beat option
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 2

    ## 랜덤포트 사용 시 eureka 등록할 인스턴스 ID를 직접 지정
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

ims:
  api:
    mt:
      service-name: ${spring.application.name}

      # 토픽 리스트
      topics:
        recv-mt:
          - RECV-MT