################################################################################################################
# IMS Api MT
################################################################################################################

spring:
  profiles:
    active: local